name: Node.js Package

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: cd npm ci
        working-directory: sample-packages/npm
      - run: npm publish
        working-directory: sample-packages/npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
